version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: jobboard
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: jobpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=jobboard
      - DJANGO_DB_USER=jobuser
      - DJANGO_DB_PASSWORD=jobpass

volumes:
  postgres_data: