# Generated by Django 5.2.5 on 2025-08-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_description_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='day_left',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
