# Generated by Django 5.2.5 on 2025-08-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_day_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
