# Generated by Django 5.2.5 on 2025-08-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
